import type { HotspotListing } from "./types";

/** Hardcoded hotspot listings shown when the control API has no live listings. */
export const LISTINGS: HotspotListing[] = [
  {
    id: "hs-001",
    name: "CafeNova Uplink",
    ssid: "HDX-CafeNova",
    location: "San Francisco, CA · Mission District",
    pricePerMinute: 0.01,
    signalStrength: 5,
    status: "available",
    host: "0xcafe...1234",
    hostIp: "192.168.2.1",
    portalUrl: "http://192.168.2.1:8888/",
    uploadMbps: 50,
    downloadMbps: 200,
  },
  {
    id: "hs-002",
    name: "RoofTop Node #7",
    ssid: "HDX-Rooftop7",
    location: "New York, NY · Lower East Side",
    pricePerMinute: 0.008,
    signalStrength: 4,
    status: "available",
    host: "0xabcd...5678",
    hostIp: "192.168.3.1",
    portalUrl: "http://192.168.3.1:8888/",
    uploadMbps: 30,
    downloadMbps: 150,
  },
  {
    id: "hs-003",
    name: "Harbor Bridge WiFi",
    ssid: "HDX-Harbor",
    location: "Seattle, WA · Pioneer Square",
    pricePerMinute: 0.015,
    signalStrength: 3,
    status: "occupied",
    host: "0xdead...beef",
    uploadMbps: 20,
    downloadMbps: 80,
  },
  {
    id: "hs-004",
    name: "Sunset Corridor AP",
    ssid: "HDX-Sunset",
    location: "Austin, TX · South Congress",
    pricePerMinute: 0.005,
    signalStrength: 4,
    status: "available",
    host: "0x1337...c0de",
    uploadMbps: 40,
    downloadMbps: 120,
  },
];
