import type { HotspotListing } from "./types";

/** Hardcoded hotspot listings shown when the control API has no live listings. */
export const LISTINGS: HotspotListing[] = [
  {
    id: "local-hotspot",
    name: "Netra Test Account",
    ssid: "⚡Netra-Netra",
    location: "Philadelphia, PA · Demo hotspot",
    pricePerMinute: 0.001,
    signalStrength: 5,
    status: "available",
    host: "Netra Test Account",
    hostWallet: "CRPNHN3oxc93MUb1JnG9JZvH8kgvXLtj3TVyaAayB2X8",
    hostIp: "192.168.2.1",
    portalUrl: "http://192.168.2.1:8888/",
    uploadMbps: 50,
    downloadMbps: 200,
    durationOptions: [5, 10, 30],
    real: true,
    reputation: {
      reliabilityScore: 98,
      successfulSessions: 41,
      refunds: 1,
      disconnectRate: 0.02,
    },
    filecoin: {
      latestReputationCid: "bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi",
    },
  },
  {
    id: "demo-fishtown-commons",
    name: "Fishtown Commons",
    ssid: "⚡Netra-Fishtown",
    location: "Philadelphia, PA · Fishtown",
    pricePerMinute: 0.0008,
    signalStrength: 4,
    status: "available",
    host: "demo-host-fishtown",
    hostWallet: "CRPNHN3oxc93MUb1JnG9JZvH8kgvXLtj3TVyaAayB2X8",
    hostIp: "192.168.2.1",
    portalUrl: "http://192.168.2.1:8888/",
    uploadMbps: 30,
    downloadMbps: 150,
    durationOptions: [5, 10, 30],
    demo: true,
    reputation: {
      reliabilityScore: 96,
      successfulSessions: 33,
      refunds: 2,
      disconnectRate: 0.05,
    },
    filecoin: {
      latestReputationCid: "bafkreifjjcie6lypi6ny7amxnfftagclbuxndqonfipmr7yooeoy3zdhhq",
    },
  },
  {
    id: "demo-old-city-relay",
    name: "Old City Relay",
    ssid: "⚡Netra-OldCity",
    location: "Philadelphia, PA · Old City",
    pricePerMinute: 0.0012,
    signalStrength: 3,
    status: "available",
    host: "demo-host-oldcity",
    hostWallet: "CRPNHN3oxc93MUb1JnG9JZvH8kgvXLtj3TVyaAayB2X8",
    hostIp: "192.168.2.1",
    portalUrl: "http://192.168.2.1:8888/",
    uploadMbps: 20,
    downloadMbps: 80,
    durationOptions: [10, 20, 30],
    demo: true,
  },
  {
    id: "demo-university-city-mesh",
    name: "University City Mesh",
    ssid: "⚡Netra-UCity",
    location: "Philadelphia, PA · University City",
    pricePerMinute: 0.0006,
    signalStrength: 4,
    status: "available",
    host: "demo-host-ucity",
    hostWallet: "CRPNHN3oxc93MUb1JnG9JZvH8kgvXLtj3TVyaAayB2X8",
    hostIp: "192.168.2.1",
    portalUrl: "http://192.168.2.1:8888/",
    uploadMbps: 40,
    downloadMbps: 120,
    durationOptions: [5, 15, 30],
    demo: true,
  },
  {
    id: "demo-riverfront-ap",
    name: "Riverfront AP",
    ssid: "⚡Netra-Riverfront",
    location: "Philadelphia, PA · Penn's Landing",
    pricePerMinute: 0.0007,
    signalStrength: 4,
    status: "available",
    host: "demo-host-riverfront",
    hostWallet: "CRPNHN3oxc93MUb1JnG9JZvH8kgvXLtj3TVyaAayB2X8",
    hostIp: "192.168.2.1",
    portalUrl: "http://192.168.2.1:8888/",
    uploadMbps: 36,
    downloadMbps: 125,
    durationOptions: [5, 10, 20],
    demo: true,
  },
];
